AllCops:
  SuggestExtensions: false

require:
  - rubocop
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

RSpec/HookArgument:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/InstanceVariable:
 Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Naming/VariableName:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 150
